server:
  port: 8111

eureka:
  instance:
    hostname: zuul
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
            defaultZone: http://nmikz:123123@eureka-server:8761/eureka/
            
spring:
  application:
    name: zuul
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS
